language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run start
deploy:
  provider: surge
  skip_cleanup: true
  domain: cot-rudra.surge.sh
  project: ./build/
on:
  branch: heroku
